<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>ProtoBuf.FSharp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" VersionOverride="8.0.200" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\protobuf-net.Core\protobuf-net.Core.csproj" />
  </ItemGroup>
</Project>
