<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>ProtoBuf.Meta</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\protobuf-net\protobuf-net.csproj" />
  </ItemGroup>
</Project>
